/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hometastic;


import java.sql.Connection;
import java.util.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class HostMainPage extends javax.swing.JFrame {
    /**
     * Creates new form HostMainPage
     */
    String username, hostid;
    
    public HostMainPage() {
        initComponents();
        show_report();
    }
    
    public HostMainPage(String username) {
        initComponents();
        this.username = username;
        this.hostid = username;
        FullName1.setText(username);
        show_report();
    }
    
    public String getHostid(){
        return hostid;
    }
    
    public Connection getConnection(){
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hometastic","root","1234");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }

    public void updateSearchTable(){
        String query = "select property.PROPERTY_ID, property.PROPERTY_NAME, property.CITY, property.STATE, property.PRICE, property.MAX_PERSON from property where property_id = "+ getHostid();
                
        try{
            Connection connection = getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            TableReport.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public ArrayList<Property> getPropertyList(){
        ArrayList<Property> propertylist = new ArrayList<Property>();
        Connection connection = getConnection();
        
        String query = "select * from property where host_id = '"+getHostid()+"'";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Property property;
            while(rs.next()){
                property = new Property(rs.getInt("PROPERTY_ID"),rs.getString("PROPERTY_NAME"),rs.getString("CITY"),rs.getString("STATE"),rs.getDouble("PRICE"),rs.getInt("MAX_PERSON"));
                //int pid = property.getPropertyID();
                propertylist.add(property);
                //propertylist.get(i).setPropertyID(pid);
                //System.out.println(propertylist.get(i).getPropertyID());
                //i++;
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
        return propertylist;
    }
    
    //Display Data
    
    public void update_table(){
        String query = "select * from property where host_id =" +getHostid();
        try{
            Connection connection = getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            TableReport.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void show_report(){
        ArrayList<Property> list = getPropertyList();
        DefaultTableModel model = (DefaultTableModel)TableReport.getModel();
        Object[] row = new Object[6];
        for(int i = 0; i < list.size(); i++){
            //System.out.println(list.get(i).getPropertyID());
            row[0] = list.get(i).getPropertyID();
            row[1] = list.get(i).getPropertyName();
            row[2] = list.get(i).getCity();
            row[3] = list.get(i).getState();
            row[4] = list.get(i).getPrice();
            row[5] = list.get(i).getMaxPerson();
            
            model.addRow(row);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        HomeMenu2 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        HomeMenu3 = new javax.swing.JButton();
        myPropertyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        FullName1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        FullName2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReport = new javax.swing.JTable();
        manageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeTastic");
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 96, 166));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeMenu2.setBackground(new java.awt.Color(0, 66, 127));
        HomeMenu2.setMinimumSize(new java.awt.Dimension(233, 45));
        HomeMenu2.setPreferredSize(new java.awt.Dimension(240, 55));
        HomeMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        HomeMenu3.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu3.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu3.setText("Account Settings");
        HomeMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenu3ActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 340, 60));

        myPropertyButton.setBackground(new java.awt.Color(0, 96, 166));
        myPropertyButton.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        myPropertyButton.setForeground(new java.awt.Color(255, 255, 255));
        myPropertyButton.setText("My Property");
        myPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPropertyButtonActionPerformed(evt);
            }
        });
        HomeMenu2.add(myPropertyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 340, 60));

        jPanel3.add(HomeMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 330, 130));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 550));

        jPanel4.setBackground(new java.awt.Color(0, 66, 127));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FullName1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        FullName1.setForeground(new java.awt.Color(255, 255, 255));
        FullName1.setText("host Name");
        FullName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullName1MouseClicked(evt);
            }
        });
        jPanel4.add(FullName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 170, 60));
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        FullName.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 255, 255));
        FullName.setText("Log Out");
        FullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullNameMouseClicked(evt);
            }
        });
        jPanel4.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        FullName2.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        FullName2.setForeground(new java.awt.Color(255, 255, 255));
        FullName2.setText("My Property");
        jPanel4.add(FullName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 160, 40));

        jButton1.setBackground(new java.awt.Color(255, 242, 0));
        jButton1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jButton1.setText("Add Property");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 85, 130, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 760, 140));

        TableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID. No", "Property Name", "City", "State", "Price/Night", "Max Person"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableReport.setRowHeight(40);
        jScrollPane1.setViewportView(TableReport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 710, 290));

        manageButton.setBackground(new java.awt.Color(0, 66, 127));
        manageButton.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        manageButton.setForeground(new java.awt.Color(255, 255, 255));
        manageButton.setText("Manage Property");
        manageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 160, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtonActionPerformed
        int row = TableReport.getSelectedRow();
        String cell = TableReport.getModel().getValueAt(row, 0).toString();
        String propname = TableReport.getModel().getValueAt(row, 1).toString();
        int propid = Integer.parseInt(cell);
        System.out.println(cell);
        Property property = null;
        //p.setPropertyID()
        dispose();
        ModifyProperty e = new ModifyProperty(username, propid, propname);
        e.setVisible(true);
        
        /*String query = "UPDATE `hometatsic`.`report` SET `REPORT_STATUS` = 'DONE' WHERE `REPORT_ID` = " + cell;
        try{
            Connection connection = getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Marked as Done!");
            update_table();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_manageButtonActionPerformed

    private void FullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullNameMouseClicked
        // TODO add your handling code here:
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_FullNameMouseClicked

    private void myPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPropertyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myPropertyButtonActionPerformed

    private void HomeMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMenu3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new AddProperty(username).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FullName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullName1MouseClicked
        // TODO add your handling code here:
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_FullName1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FullName;
    private javax.swing.JLabel FullName1;
    private javax.swing.JLabel FullName2;
    private javax.swing.JPanel HomeMenu2;
    private javax.swing.JButton HomeMenu3;
    private javax.swing.JLabel Menu;
    private javax.swing.JTable TableReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageButton;
    private javax.swing.JButton myPropertyButton;
    // End of variables declaration//GEN-END:variables
}
