/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hometastic;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
        getData();
    }
    String username, homestayname;
    int bookingid, propid, paymentid;
    double paid;
    String date;
    
    public Invoice(int bookingid, String username, String homestayname, double paid, String date) {
        initComponents();
        this.bookingid = bookingid;
        this.username = username;
        this.homestayname = homestayname;
        this.paid = paid;
        this.date = date;
        getData();
        homestayName.setText(homestayname);
    }
    
     public Invoice(int propid, String username, String homestayname, int e) {
        initComponents();
        this.propid = propid;
        this.username = username;
        this.paymentid = e;
        this.homestayname = homestayname;
        
        getData();
        homestayName.setText(homestayname);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userName1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        booking_id1 = new javax.swing.JLabel();
        homestayName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        booking_id = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        total_price1 = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        amountPaid = new javax.swing.JLabel();
        jLabeldate = new javax.swing.JLabel();
        savePDFButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        property_type = new javax.swing.JLabel();
        userName3 = new javax.swing.JLabel();
        location1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeTastic");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 96, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 55, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 66, 127));

        jButton1.setBackground(new java.awt.Color(0, 66, 127));
        jButton1.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 66, 127));
        jButton2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("My Bookings");

        jButton3.setBackground(new java.awt.Color(0, 66, 127));
        jButton3.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Account Settings");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 330, 230));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometastic/Logo3a.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 830));

        jPanel2.setBackground(new java.awt.Color(0, 66, 127));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        userName1.setForeground(new java.awt.Color(255, 255, 255));
        userName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometastic/user2w.png"))); // NOI18N
        userName1.setText("User's Username");
        jPanel2.add(userName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 34));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Invoice");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 275, 80));

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Log Out");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 900, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booking_id1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        booking_id1.setText("#GCJWHCS19");
        jPanel3.add(booking_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 31));

        homestayName.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        homestayName.setText("Homestay Kelantan Darul Naim");
        jPanel3.add(homestayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 650, 60));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel7.setText("Thank you for your interest in using our application to find and book a homestay.  ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 760, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel8.setText("Check out the details of your payment below.");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 31));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 66, 127));

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Payment Details");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel9)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 660, 40));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel10.setText("Booking ID            :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 27));

        booking_id.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        booking_id.setText("GCJWHCS19");
        jPanel4.add(booking_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, 27));

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel16.setText("Amount Paid         :     RM");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 230, 27));

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel17.setText("Date Received       :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 27));

        total_price1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        total_price1.setText("Total Price             :     RM");
        jPanel4.add(total_price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 27));

        total_price.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        total_price.setText("10.00");
        jPanel4.add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, 27));

        amountPaid.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        amountPaid.setText("90.00");
        jPanel4.add(amountPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, 27));

        jLabeldate.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabeldate.setText("DD/MM/YYYY");
        jPanel4.add(jLabeldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, 27));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 660, 230));

        savePDFButton.setBackground(new java.awt.Color(0, 66, 127));
        savePDFButton.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        savePDFButton.setForeground(new java.awt.Color(255, 255, 255));
        savePDFButton.setText("Save as PDF");
        savePDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePDFButtonActionPerformed(evt);
            }
        });
        jPanel3.add(savePDFButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 160, 50));

        exitButton.setBackground(new java.awt.Color(0, 66, 127));
        exitButton.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit to Home");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 170, 50));

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel11.setText("Hello ");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel12.setText("Booking ID: ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 31));

        property_type.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        property_type.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometastic/Asset 10.png"))); // NOI18N
        property_type.setText("Bungalow");
        jPanel3.add(property_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 40));

        userName3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        userName3.setText("User's First Name, ");
        jPanel3.add(userName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 40));

        location1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        location1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometastic/Asset 7.png"))); // NOI18N
        location1.setText("Bachok, Kelantan");
        jPanel3.add(location1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 900, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getData() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hometastic", "root", "1234");

            PreparedStatement statement = conn.prepareStatement("select * from property where property_id ="+ propid);
            ResultSet rs = statement.executeQuery();

            while(rs.next()) {
                homestayName.setText(rs.getString("property_name"));
                location1.setText(rs.getString("city") + ", " + rs.getString("state"));
                property_type.setText(rs.getString("property_type"));
            }
            
            PreparedStatement bStatement = conn.prepareStatement("select * from booking where property_id ="+propid);
            ResultSet rs1 = bStatement.executeQuery();
            
            while(rs1.next()){
                //userName.setText(rs1.getString("user_id")); //user's name kat atas sekali
                userName3.setText(rs1.getString("user_id"));
                userName1.setText(rs1.getString("user_id") + ",");
                jLabeldate.setText(rs1.getString("booking_date"));
                booking_id.setText("#" + rs1.getString("booking_id"));
                booking_id1.setText("#" + rs1.getString("booking_id"));
            }
            
            PreparedStatement pStatement = conn.prepareStatement("select * from payment where payment_id ="+paymentid);
            ResultSet rs2 = pStatement.executeQuery();
            
            while(rs2.next()){
                total_price.setText(rs2.getString("total_price"));
                amountPaid.setText(rs2.getString("total_paid"));
            }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainPage(username).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainPage(username).setVisible(true);
        //new QuickHome_MasterDesign().setVisible(true)
    }//GEN-LAST:event_exitButtonActionPerformed

    private void savePDFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePDFButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_savePDFButtonActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPaid;
    private javax.swing.JLabel booking_id;
    private javax.swing.JLabel booking_id1;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel homestayName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel location1;
    private javax.swing.JLabel property_type;
    private javax.swing.JButton savePDFButton;
    private javax.swing.JLabel total_price;
    private javax.swing.JLabel total_price1;
    private javax.swing.JLabel userName1;
    private javax.swing.JLabel userName3;
    // End of variables declaration//GEN-END:variables
}


