/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hometastic;

/**
 *
 * @author user
 */
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class MakeReport extends javax.swing.JFrame {

    /**
     * Creates new form MakeReport
     */
    public MakeReport() {
        initComponents();
    }
    
    public String username;
    public MakeReport(String username) {
        initComponents();
        this.username = username;
        jLabelusername.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        HomeMenu2 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        HomeMenu = new javax.swing.JButton();
        HomeMenu1 = new javax.swing.JButton();
        HomeMenu3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        PageTitle = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        jLabelusername = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Issues = new javax.swing.JLabel();
        Performance = new javax.swing.JRadioButton();
        FalseReview = new javax.swing.JRadioButton();
        Technical = new javax.swing.JRadioButton();
        Fraud = new javax.swing.JRadioButton();
        Payment = new javax.swing.JRadioButton();
        Account = new javax.swing.JRadioButton();
        RateApps1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CommentArea = new javax.swing.JTextArea();
        CancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeTastic");
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 96, 166));
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 900));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeMenu2.setBackground(new java.awt.Color(0, 66, 127));
        HomeMenu2.setMinimumSize(new java.awt.Dimension(233, 45));
        HomeMenu2.setPreferredSize(new java.awt.Dimension(240, 55));
        HomeMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        HomeMenu.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu.setText("Account Settings");
        HomeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenuActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 350, 60));

        HomeMenu1.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu1.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu1.setText("Home");
        HomeMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomeMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenu1ActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        HomeMenu3.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu3.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu3.setText("My Bookings");
        HomeMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenu3ActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 350, 60));

        jPanel3.add(HomeMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 350, 180));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, -1));
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometastic/Logo3a.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 130, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 720));

        jPanel4.setBackground(new java.awt.Color(0, 66, 127));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PageTitle.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        PageTitle.setForeground(new java.awt.Color(255, 255, 255));
        PageTitle.setText("Make Report");
        jPanel4.add(PageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 60, 250, -1));

        FullName.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 255, 255));
        FullName.setText("Log Out");
        FullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullNameMouseClicked(evt);
            }
        });
        jPanel4.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabelusername.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabelusername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusername.setText("User's Username");
        jPanel4.add(jLabelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hometastic/user2w.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 830, 130));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Issues.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        Issues.setText("Issues");
        Issues.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                IssuesAncestorResized(evt);
            }
        });
        jPanel5.add(Issues, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        buttonGroup1.add(Performance);
        Performance.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        Performance.setText("Performance");
        Performance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformanceActionPerformed(evt);
            }
        });
        jPanel5.add(Performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        buttonGroup1.add(FalseReview);
        FalseReview.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        FalseReview.setText("False Review");
        FalseReview.setActionCommand("FalseReview");
        FalseReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalseReviewActionPerformed(evt);
            }
        });
        jPanel5.add(FalseReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        buttonGroup1.add(Technical);
        Technical.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        Technical.setText("Technical");
        Technical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TechnicalActionPerformed(evt);
            }
        });
        jPanel5.add(Technical, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        buttonGroup1.add(Fraud);
        Fraud.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        Fraud.setText("Fraud");
        Fraud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FraudActionPerformed(evt);
            }
        });
        jPanel5.add(Fraud, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        buttonGroup1.add(Payment);
        Payment.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        Payment.setText("Payment");
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });
        jPanel5.add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        buttonGroup1.add(Account);
        Account.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        Account.setText("Account");
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });
        jPanel5.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        RateApps1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        RateApps1.setText("Rate our apps!");
        jPanel5.add(RateApps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 66, 127));

        jLabel1.setBackground(new java.awt.Color(0, 66, 127));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comments");
        jPanel1.add(jLabel1);

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 550, 30));

        CommentArea.setColumns(20);
        CommentArea.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        CommentArea.setRows(5);
        CommentArea.setText("Enter comment here\n\nUser must enter comment maximum 280 words\nAll actor can make report");
        CommentArea.setToolTipText("");
        jScrollPane2.setViewportView(CommentArea);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 550, 110));

        CancelButton.setBackground(new java.awt.Color(153, 0, 0));
        CancelButton.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel5.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 140, 40));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        SubmitButton.setBackground(new java.awt.Color(0, 66, 127));
        SubmitButton.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel5.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 140, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 830, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerformanceActionPerformed

    private void FalseReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalseReviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FalseReviewActionPerformed

    private void TechnicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TechnicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TechnicalActionPerformed

    private void FraudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FraudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FraudActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountActionPerformed

    private void IssuesAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_IssuesAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuesAncestorResized

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainPage(username).setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        Account.setActionCommand("Account");
        FalseReview.setActionCommand("FalseReview");
        Payment.setActionCommand("Payment");
        Performance.setActionCommand("Performance");
        Technical.setActionCommand("Technical");
        Fraud.setActionCommand("Fraud");
        String selection = buttonGroup1.getSelection().getActionCommand();
        
        String comment = CommentArea.getText();
        
        Connection conn = null;
        PreparedStatement statement = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hometastic", "root", "1234");
            statement = conn.prepareStatement("insert into report values(null,?,?,?)");
            statement.setString(1, selection);
            statement.setString(2, comment);
            statement.setString(3, null);
            int i = statement.executeUpdate();
            if(i > 0) {
                JOptionPane.showMessageDialog(null, "Report sent!");
            }
            else {
                JOptionPane.showMessageDialog(null, "Report is failed to send");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        dispose();
        new MainPage(username).setVisible(true);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void HomeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMenuActionPerformed

    private void HomeMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMenu3ActionPerformed

    private void HomeMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenu1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainPage(username).setVisible(true);
    }//GEN-LAST:event_HomeMenu1ActionPerformed

    private void FullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullNameMouseClicked
        // TODO add your handling code here:
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_FullNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Account;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextArea CommentArea;
    private javax.swing.JRadioButton FalseReview;
    private javax.swing.JRadioButton Fraud;
    private javax.swing.JLabel FullName;
    private javax.swing.JButton HomeMenu;
    private javax.swing.JButton HomeMenu1;
    private javax.swing.JPanel HomeMenu2;
    private javax.swing.JButton HomeMenu3;
    private javax.swing.JLabel Issues;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel PageTitle;
    private javax.swing.JRadioButton Payment;
    private javax.swing.JRadioButton Performance;
    private javax.swing.JLabel RateApps1;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JRadioButton Technical;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
