/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hometastic;

import java.sql.Connection;
import java.util.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class ManageReport extends javax.swing.JFrame {
    /**
     * Creates new form Welcome
     */
    public String username;
    public ManageReport() {
        initComponents();
        show_report();
    }
    
    public ManageReport(String username) {
        initComponents();
        jLabeladmin.setText(username);
        this.username = username;
        show_report();
    }
    
    public Connection getConnection(){
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hometastic","root","1234");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
    
    public ArrayList<Report> getreportList(){
        ArrayList<Report> reportlist = new ArrayList<Report>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM REPORT";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Report report;
            while(rs.next()){
                report = new Report(rs.getInt("REPORT_ID"),rs.getString("REPORT_TYPE"),rs.getString("REPORT_DESC"),rs.getString("REPORT_STATUS"));
                reportlist.add(report);
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
        return reportlist;
    }
    
    //Display Data
    
    public void update_table(){
        String query = "select * from report";
        try{
            Connection connection = getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            TableReport.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void show_report(){
        ArrayList<Report> list = getreportList();
        DefaultTableModel model = (DefaultTableModel)TableReport.getModel();
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++){
            row[0] = list.get(i).getReportID();
            row[1] = list.get(i).getReportType();
            row[2] = list.get(i).getReportDesc();
            row[3] = list.get(i).getReportStatus();
            
            model.addRow(row);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        HomeMenu2 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        ManageReportButton = new javax.swing.JButton();
        HomeMenu1 = new javax.swing.JButton();
        HomeMenu3 = new javax.swing.JButton();
        HomeMenu4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        PageTitle = new javax.swing.JLabel();
        jLabeladmin = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        FullName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReport = new javax.swing.JTable();
        jDoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomeTastic");
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 96, 166));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeMenu2.setBackground(new java.awt.Color(0, 66, 127));
        HomeMenu2.setMinimumSize(new java.awt.Dimension(233, 45));
        HomeMenu2.setPreferredSize(new java.awt.Dimension(240, 55));
        HomeMenu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        ManageReportButton.setBackground(new java.awt.Color(0, 96, 166));
        ManageReportButton.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        ManageReportButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageReportButton.setText("Manage Report");
        ManageReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageReportButtonActionPerformed(evt);
            }
        });
        HomeMenu2.add(ManageReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, 370, 60));

        HomeMenu1.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu1.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu1.setText("Property Approval");
        HomeMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HomeMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenu1ActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 370, 60));

        HomeMenu3.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu3.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu3.setText("Account Settings");
        HomeMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenu3ActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 350, 60));

        HomeMenu4.setBackground(new java.awt.Color(0, 96, 166));
        HomeMenu4.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        HomeMenu4.setForeground(new java.awt.Color(255, 255, 255));
        HomeMenu4.setText("Property Manager");
        HomeMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenu4ActionPerformed(evt);
            }
        });
        HomeMenu2.add(HomeMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 370, 60));

        jPanel3.add(HomeMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 110, 360, 240));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        jPanel4.setBackground(new java.awt.Color(0, 66, 127));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PageTitle.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        PageTitle.setForeground(new java.awt.Color(255, 255, 255));
        PageTitle.setText("Manage Report");
        jPanel4.add(PageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 40));

        jLabeladmin.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabeladmin.setForeground(new java.awt.Color(255, 255, 255));
        jLabeladmin.setText("Admin's Full Name");
        jPanel4.add(jLabeladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 96, 166));
        jTextField1.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("     Search Report");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 340, 30));

        FullName.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(255, 255, 255));
        FullName.setText("Log Out");
        FullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullNameMouseClicked(evt);
            }
        });
        jPanel4.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 760, 110));

        TableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report ID", "Type", "Description", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableReport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 710, 350));

        jDoneButton.setBackground(new java.awt.Color(0, 66, 127));
        jDoneButton.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jDoneButton.setForeground(new java.awt.Color(255, 255, 255));
        jDoneButton.setText("Mark as Done");
        jDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jDoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 140, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReportButtonActionPerformed
        
    }//GEN-LAST:event_ManageReportButtonActionPerformed

    private void HomeMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMenu1ActionPerformed

    private void HomeMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMenu3ActionPerformed

    private void HomeMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeMenu4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoneButtonActionPerformed
        int row = TableReport.getSelectedRow();
        String cell = TableReport.getModel().getValueAt(row, 0).toString();
        String query = "UPDATE `hometastic`.`report` SET `REPORT_STATUS` = 'DONE' WHERE `REPORT_ID` = " + cell;
        try{
            Connection connection = getConnection();
            PreparedStatement ps = connection.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Marked as Done!");
            update_table();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jDoneButtonActionPerformed

    private void FullNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullNameMouseClicked
        // TODO add your handling code here:
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_FullNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FullName;
    private javax.swing.JButton HomeMenu1;
    private javax.swing.JPanel HomeMenu2;
    private javax.swing.JButton HomeMenu3;
    private javax.swing.JButton HomeMenu4;
    private javax.swing.JButton ManageReportButton;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel PageTitle;
    private javax.swing.JTable TableReport;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jDoneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabeladmin;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
